# Generated by Django 4.1.6 on 2023-03-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('categoryDes', models.CharField(max_length=300)),
                ('categoryImage', models.ImageField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=50)),
                ('uImage', models.ImageField(upload_to='User_images/')),
                ('akaName', models.CharField(max_length=50)),
                ('uAbout', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('image_url', models.ImageField(upload_to='recipe_images/')),
                ('likes', models.IntegerField(default=0)),
                ('recipe_type', models.BooleanField(choices=[(True, 'Veg'), (False, 'Non-Veg')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.user')),
            ],
        ),
    ]
